#!bin/bash
#Firewall configuration script for CENTOS 


#Open Ports
#Web Ports
sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 80 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 443 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 8080 -j ACCEPT

#MySQL
sudo iptables -A INPUT -p tcp --dport 3306 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 3306 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 33060 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 33060 -j ACCEPT

#SSH
sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 22 -j ACCEPT

#Email
sudo iptables -A INPUT -p tcp --dport 587 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 587 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 993 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 993 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 995 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 995 -j ACCEPT
 
#Close Ports
#TelNet
sudo iptables -A INPUT -p tcp --dport 23 -j DROP
sudo iptables -A INPUT -p udp --dport 23 -j DROP

#ICMP (ping)
sudo iptables -A INPUT -p tcp --dport 5813 -j DROP
sudo iptables -A INPUT -p udp --dport 5813 -j DROP

#Block IPs
sudo iptables -I INPUT -s 192.168.139.250 -j DROP

#Block MACs
sudo iptables -A INPUT -m mac --mac-source 00:00:00:00:00:AA -j DROP

#PortForwarding
#80 to 8080
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.139.137:8080
iptables -t nat -A PREROUTING -p udp --dport 80 -j DNAT --to-destination 192.168.139.137:8080

#saves firewall configuration
sudo service iptables save
#!bin/bash
#Firewall configuration script for CENTOS 


#Open Ports
#Web Ports
sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 80 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 443 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 8080 -j ACCEPT

#MySQL
sudo iptables -A INPUT -p tcp --dport 3306 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 3306 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 33060 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 33060 -j ACCEPT

#SSH
sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 22 -j ACCEPT

#Email
sudo iptables -A INPUT -p tcp --dport 587 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 587 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 993 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 993 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 995 -j ACCEPT
sudo iptables -A INPUT -p udp --dport 995 -j ACCEPT
 
#Close Ports
#TelNet
sudo iptables -A INPUT -p tcp --dport 23 -j DROP
sudo iptables -A INPUT -p udp --dport 23 -j DROP

#ICMP (ping)
sudo iptables -A INPUT -p tcp --dport 5813 -j DROP
sudo iptables -A INPUT -p udp --dport 5813 -j DROP

#Block IPs
sudo iptables -I INPUT -s 192.168.139.250 -j DROP

#Block MACs
sudo iptables -A INPUT -m mac --mac-source 00:00:00:00:00:AA -j DROP

#PortForwarding
#80 to 8080
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.139.137:8080
iptables -t nat -A PREROUTING -p udp --dport 80 -j DNAT --to-destination 192.168.139.137:8080

#saves firewall configuration
sudo iptables-save
